repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args:
          - "--target-version=py310"
          - "--target-version=py311"
          - "--target-version=py312"
        exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - "--profile=black"
          - "--project=polls"
          - "--thirdparty=django"
          - "--thirdparty=faker"
        exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          -  "--max-line-length=88"
          -  "--extend-ignore=E203"
          -  "--per-file-ignores=mysite/settings.py:E501"
        exclude: ^.*\b(migrations)\b.*$
