services:
  postgres:
    restart: always
    image: postgres:alpine
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dbpass}

  django:
    restart: always
    build: .
    expose:
      - 8000
    volumes:
      - static-data:/app/static
    depends_on:
      - postgres
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY
      - STATIC_URL=${STATIC_URL:-static/}
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dbpass}
      - POSTGRES_HOST=postgres
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - static-data:/usr/share/nginx/html/static:ro
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - django
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME:-localhost}
      - NGINX_DJANGO_HOST=django

volumes:
  db-data:
  static-data:
